export const data = [
  {
    id: 1,
    src: '/assets/icons/lev-haolam.svg',
    result: '$20K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Lev Haolam',
    product: 'Handmade gifts from Israel',
    platform: 'Klaviyo',
    sizeWidth: { xs: '150px', md: '170px', lg: '200px', desktop: '250px' },
    sizeHeight: { xs: '55px', md: '65px', lg: '76px', desktop: '92px' },
  },
  {
    id: 2,
    src: '/assets/icons/schneider-electric.svg',
    result: '$40K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Schneider Electric',
    product: 'Electrical equipment from France',
    platform: 'Klaviyo',
    sizeWidth: { xs: '150px', md: '170px', lg: '200px', desktop: '250px' },
    sizeHeight: { xs: '49px', md: '50px', lg: '59px', desktop: '74px' },
  },
  {
    id: 3,
    src: '/assets/icons/aliexpress.svg',
    result: '$100K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Aliexpress',
    product: 'Delivery of inexpensive products worldwide from China',
    platform: 'Klaviyo',
    sizeWidth: { xs: '150px', md: '170px', lg: '200px', desktop: '250px' },
    sizeHeight: { xs: '42px', md: '41px', lg: '48px', desktop: '60px' },
  },
  {
    id: 4,
    src: '/assets/icons/la-roche-posay.svg',
    result: '$70K per email campaign',
    type: 'Subscription e-commerce',
    company: 'La Roche-Posay',
    product: 'Products for different skin types from France',
    platform: 'Klaviyo',
    sizeWidth: { xs: '150px', md: '170px', lg: '200px', desktop: '250px' },
    sizeHeight: { xs: '68px', md: '74px', lg: '87px', desktop: '109px' },
  },
  {
    id: 5,
    src: '/assets/icons/papajohns.svg',
    result: '$85K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Papajohns',
    product: 'Pizza making and delivery from USA',
    platform: 'Klaviyo',
    sizeWidth: { xs: '150px', md: '170px', lg: '200px', desktop: '250px' },
    sizeHeight: { xs: '35px', md: '31px', lg: '37px', desktop: '46px' },
  },
  {
    id: 6,
    src: '/assets/icons/kfc.svg',
    result: '$60K per email campaign',
    type: 'Subscription e-commerce',
    company: 'KFC',
    product: 'Fast food dishes from USA',
    platform: 'Klaviyo',
    sizeWidth: { xs: '150px', md: '170px', lg: '200px', desktop: '250px' },
    sizeHeight: { xs: '49px', md: '50px', lg: '59px', desktop: '74px' },
  },
];
