export const data = [
  {
    id: 1,
    src: '/assets/icons/lev-haolam.svg',
    result: '$20K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Lev Haolam',
    product: 'Handmade gifts from Israel',
    platform: 'Klaviyo',
    sizeWidth: { xs: '70.23px', md: '100px', lg: '130px', desktop: '180px' },
    sizeHeight: { xs: '26.03px', md: '38px', lg: '49px', desktop: '166.72px' },
  },
  {
    id: 2,
    src: '/assets/icons/schneider-electric.svg',
    result: '$40K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Schneider Electric',
    product: 'Electrical equipment from France',
    platform: 'Klaviyo',
    sizeWidth: { xs: '70.23px', md: '100px', lg: '130px', desktop: '180px' },
    sizeHeight: { xs: '20.72px', md: '30px', lg: '38px', desktop: '53.1px' },
  },
  {
    id: 3,
    src: '/assets/icons/aliexpress.svg',
    result: '$100K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Aliexpress',
    product: 'Delivery of inexpensive products worldwide from China',
    platform: 'Klaviyo',
    sizeWidth: { xs: '70.23px', md: '100px', lg: '130px', desktop: '180px' },
    sizeHeight: { xs: '16.33px', md: '24px', lg: '31px', desktop: '41.85px' },
  },
  {
    id: 4,
    src: '/assets/icons/la-roche-posay.svg',
    result: '$70K per email campaign',
    type: 'Subscription e-commerce',
    company: 'La Roche-Posay',
    product: 'Products for different skin types from France',
    platform: 'Klaviyo',
    sizeWidth: { xs: '70.23px', md: '100px', lg: '130px', desktop: '180px' },
    sizeHeight: { xs: '30.02px', md: '44px', lg: '57px', desktop: '76.95px' },
  },
  {
    id: 5,
    src: '/assets/icons/papajohns.svg',
    result: '$85K per email campaign',
    type: 'Subscription e-commerce',
    company: 'Papajohns',
    product: 'Pizza making and delivery from USA',
    platform: 'Klaviyo',
    sizeWidth: { xs: '70.23px', md: '100px', lg: '130px', desktop: '180px' },
    sizeHeight: { xs: '12.99px', md: '18px', lg: '24px', desktop: '23.3px' },
  },
  {
    id: 6,
    src: '/assets/icons/kfc.svg',
    result: '$60K per email campaign',
    type: 'Subscription e-commerce',
    company: 'KFC',
    product: 'Fast food dishes from USA',
    platform: 'Klaviyo',
    sizeWidth: { xs: '70.23px', md: '100px', lg: '130px', desktop: '180px' },
    sizeHeight: { xs: '20.89px', md: '30px', lg: '38px', desktop: '53.55px' },
  },
];
