import { HeroProps, FooterProps } from './interfaces';

export const heroData: HeroProps[] = [
  {
    id: 1,
    name: 'lev-haolam',
    src: '/assets/icons/lev-haolam.svg',
    loading: 'eager',
    mobile: { width: '70.23px', height: '26.03px' },
    tablet: { width: '100px', height: '38px' },
    laptop: { width: '130px', height: '49px' },
    desktop: { width: '180px', height: '66.72px' },
  },
  {
    id: 2,
    name: 'schneider-electric',
    src: '/assets/icons/schneider-electric.svg',
    loading: 'lazy',
    mobile: { width: '70.23px', height: '20.72px' },
    tablet: { width: '100px', height: '30px' },
    laptop: { width: '130px', height: '38px' },
    desktop: { width: '180px', height: '53.1px' },
  },
  {
    id: 3,
    name: 'aliexpress',
    src: '/assets/icons/aliexpress.svg',
    loading: 'lazy',
    mobile: { width: '70.23px', height: '16.33px' },
    tablet: { width: '100px', height: '24px' },
    laptop: { width: '130px', height: '31px' },
    desktop: { width: '180px', height: '41.85px' },
  },
  {
    id: 4,
    name: 'la-roche-posay',
    src: '/assets/icons/la-roche-posay.svg',
    loading: 'eager',
    mobile: { width: '70.23px', height: '30.02px' },
    tablet: { width: '100px', height: '44px' },
    laptop: { width: '130px', height: '57px' },
    desktop: { width: '180px', height: '76.95px' },
  },
  {
    id: 5,
    name: 'papajohns',
    src: '/assets/icons/papajohns.svg',
    loading: 'lazy',
    mobile: { width: '70.23px', height: '12.99px' },
    tablet: { width: '100px', height: '18px' },
    laptop: { width: '130px', height: '24px' },
    desktop: { width: '180px', height: '33.3px' },
  },
  {
    id: 6,
    name: 'kfc',
    src: '/assets/icons/kfc.svg',
    loading: 'lazy',
    mobile: { width: '70.23px', height: '20.89px' },
    tablet: { width: '100px', height: '30px' },
    laptop: { width: '130px', height: '38px' },
    desktop: { width: '180px', height: '53.55px' },
  },
];

export const footerData: FooterProps[] = [
  { id: 1, name: 'twitter', src: '/assets/icons/twitter.svg', loading: 'eager', size: '40px' },
  { id: 2, name: 'instagram', src: '/assets/icons/instagram.svg', loading: 'lazy', size: '40px' },
  { id: 3, name: 'facebook', src: '/assets/icons/facebook.svg', loading: 'eager', size: '40px' },
];
